# Generated by Django 5.2.3 on 2025-06-19 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_remove_post_image_postimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postimage',
            name='image',
            field=models.ImageField(default=None, upload_to='post_images/'),
            preserve_default=False,
        ),
    ]
