# Generated by Django 5.2.3 on 2025-06-23 19:52

import django.core.validators
import posts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_post_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='location',
        ),
        migrations.RemoveField(
            model_name='post',
            name='location',
        ),
        migrations.AlterField(
            model_name='postimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='posts/', validators=[posts.models.validate_image_size, django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'webp'])]),
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
