### 1. Тестирование регистрации и аутентификации

### 1. Регистрация нового пользователя
POST http://127.0.0.1:8000/api/register/
Content-Type: application/json

{
  "username": "user1",
  "email": "user1@mail.ru",
  "password": "qawsedr1"
}


### 1.2 Получение токена (авторизация)
POST http://127.0.0.1:8000/api/token/
Content-Type: application/json

{
  "username": "user1",
  "password": "qawsedr1"
}

### 2. Тестирование постов

### 2.1 Просмотр постов без авторизации (должен работать)
GET http://127.0.0.1:8000/api/posts/
Content-Type: application/json

### 2.2 Попытка создания поста без авторизации (должна быть ошибка 401)
POST http://127.0.0.1:8000/api/posts/
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="text"

Попытка без авторизации
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="image"; filename="test.jpg"
Content-Type: image/jpeg

< ./test.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW--

### 2.3 Создание поста с авторизацией (должен работать)
POST http://127.0.0.1:8000/api/posts/
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzUwOTUyNjQxLCJpYXQiOjE3NTA5NTIzNDEsImp0aSI6IjA2MjAwODg0MGEzMzQyYzE5ZjZkYWYwODk1MjIxNjM4IiwidXNlcl9pZCI6NzV9.QT0SZABwdqzg_uzWuk3etqeB-yIyOhXpt1GLYqlTRPM

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="text"

Мой первый пост
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="image"; filename="test.jpg"
Content-Type: image/jpeg

< ./test.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW--

### 3. Тестирование комментариев

### 3.1 Создание комментария без авторизации (должна быть ошибка 401)
POST http://127.0.0.1:8000/api/posts/1/comments/
Content-Type: application/json

{
  "text": "Попытка без авторизации"
}

### 3.2 Создание комментария с авторизацией (должен работать)
POST http://127.0.0.1:8000/api/posts/206/comments/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzUwOTUyOTY0LCJpYXQiOjE3NTA5NTI2NjQsImp0aSI6ImIxM2VlYTM3Mzk3NTRjYmU4YzgzMDg5NGVkODhhNGFiIiwidXNlcl9pZCI6NzV9.-jUU9P0RjpRegI-tUNtNWWS4nsMlafV8pk-fVfvn2Pk

{
  "text": "Отличный пост! Класс!!"
}

### Получить список всех постов
GET http://127.0.0.1:8000/api/posts/
Content-Type: application/json

### 3.3 Просмотр комментариев без авторизации (должен работать)
GET http://127.0.0.1:8000/api/posts/187/comments/
Content-Type: application/json

### 4. Тестирование лайков

### 4.1 Поставить лайк без авторизации (должна быть ошибка 401)
POST http://127.0.0.1:8000/api/posts/1/like/
Content-Type: application/json

### 4.2 Поставить лайк с авторизацией (должен работать)
POST http://127.0.0.1:8000/api/posts/205/like/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzUwOTUyNjQxLCJpYXQiOjE3NTA5NTIzNDEsImp0aSI6IjA2MjAwODg0MGEzMzQyYzE5ZjZkYWYwODk1MjIxNjM4IiwidXNlcl9pZCI6NzV9.QT0SZABwdqzg_uzWuk3etqeB-yIyOhXpt1GLYqlTRPM

### 4.3 Убрать лайк (повторный запрос)
POST http://127.0.0.1:8000/api/posts/205/like/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzUwOTUyNjQxLCJpYXQiOjE3NTA5NTIzNDEsImp0aSI6IjA2MjAwODg0MGEzMzQyYzE5ZjZkYWYwODk1MjIxNjM4IiwidXNlcl9pZCI6NzV9.QT0SZABwdqzg_uzWuk3etqeB-yIyOhXpt1GLYqlTRPM

### 5. Тестирование прав доступа

### 5.1 Попытка удалить чужой пост (должна быть ошибка 403)
DELETE http://127.0.0.1:8000/api/posts/1/
Content-Type: application/json
Authorization: Bearer eiJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzUwODc3ODU4LCJpYXQiOjE3NTA4Nzc1NTgsImp0aSI6ImYwYjQxYWNiM2U4NTRkMjZiNzRhMWY4M2ZkYjA0YzAwIiwidXNlcl9pZCI6NjV9.94-ORG3Y0Hp3KajtjRReQJdDRc9UZt5Mw9h0S5UYars

### 5.2 Удаление своего поста (должен работать)
DELETE http://127.0.0.1:8000/api/posts/206/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzUwOTUzMDc5LCJpYXQiOjE3NTA5NTI3NzksImp0aSI6IjBjNzg1N2FmMjUyMTRlMmQ5ZGIwNmE5NzFlN2I0ZDEyIiwidXNlcl9pZCI6NzV9.a5CJ20KsvYoQl8pS20oQOwdek5fbXXdGrwzG8Lbg_Ww

### 6.1 Попытка редактирования поста без авторизации (должна быть ошибка 401)
PUT http://127.0.0.1:8000/api/posts/190/
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="text"

Попытка редактирования без авторизации
------WebKitFormBoundary7MA4YWxkTrZu0gW--

### 6.2 Попытка редактирования чужого поста (должна быть ошибка 403)
PUT http://127.0.0.1:8000/api/posts/190/
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzUwODc4NTU0LCJpYXQiOjE3NTA4NzgyNTQsImp0aSI6IjhmMjZiYjFhODI5NDRmYjliOWI0MDUwMDc5ZmM3MDI1IiwidXNlcl9pZCI6NjV9.y76j012N7x4DdozLdMFG5Nls1Qkv-pseTqdah0pb3js

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="text"

Попытка редактирования чужого поста
------WebKitFormBoundary7MA4YWxkTrZu0gW--

### 6.3 Успешное редактирование своего поста (должен работать)
PUT http://127.0.0.1:8000/api/posts/206/
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzUwOTUyNjQxLCJpYXQiOjE3NTA5NTIzNDEsImp0aSI6IjA2MjAwODg0MGEzMzQyYzE5ZjZkYWYwODk1MjIxNjM4IiwidXNlcl9pZCI6NzV9.QT0SZABwdqzg_uzWuk3etqeB-yIyOhXpt1GLYqlTRPM

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="text"

Обновлённый текст поста
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="image"; filename="new_image.jpg"
Content-Type: image/jpeg

< ./new_image.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW--

### 7.1 Попытка удаления комментария без авторизации (должна быть ошибка 401)
DELETE http://127.0.0.1:8000/api/comments/190/delete/
Content-Type: application/json

### 7.2 Попытка удаления чужого комментария (должна быть ошибка 403)
DELETE http://127.0.0.1:8000/api/comments/190/delete/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzUwODc4NTU0LCJpYXQiOjE3NTA4NzgyNTQsImp0aSI6IjhmMjZiYjFhODI5NDRmYjliOWI0MDUwMDc5ZmM3MDI1IiwidXNlcl9pZCI6NjV9.y76j012N7x4DdozLdMFG5Nls1Qkv-pseTqdah0pb3js

### 7.3 Удаление своего комментария (должен работать)
DELETE http://127.0.0.1:8000/api/comments/206/delete/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzUwOTUyOTY0LCJpYXQiOjE3NTA5NTI2NjQsImp0aSI6ImIxM2VlYTM3Mzk3NTRjYmU4YzgzMDg5NGVkODhhNGFiIiwidXNlcl9pZCI6NzV9.-jUU9P0RjpRegI-tUNtNWWS4nsMlafV8pk-fVfvn2Pk

### 7.4 Удаление комментария к своему посту (должен работать, даже если комментарий не ваш)
DELETE http://127.0.0.1:8000/api/comments/50/delete/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzUwOTUzMDc5LCJpYXQiOjE3NTA5NTI3NzksImp0aSI6IjBjNzg1N2FmMjUyMTRlMmQ5ZGIwNmE5NzFlN2I0ZDEyIiwidXNlcl9pZCI6NzV9.a5CJ20KsvYoQl8pS20oQOwdek5fbXXdGrwzG8Lbg_Ww