### 1. Тестирование регистрации и аутентификации

### 1. Регистрация нового пользователя
POST http://127.0.0.1:8000/api/register/
Content-Type: application/json

{
  "username": "user6",
  "email": "user6@mail.ru",
  "password": "qawsedr6"
}


### 1.2 Получение токена (авторизация)
POST http://127.0.0.1:8000/api/token/
Content-Type: application/json

{
  "username": "user1",
  "password": "qawsedr1"
}

### 2. Тестирование постов

### 2.1 Просмотр постов без авторизации (должен работать)
GET http://127.0.0.1:8000/api/posts/
Content-Type: application/json

### 2.2 Попытка создания поста без авторизации (должна быть ошибка 401)
POST http://127.0.0.1:8000/api/posts/
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="text"

Попытка без авторизации
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="image"; filename="test.jpg"
Content-Type: image/jpeg

< ./test.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW--

### 2.3 Создание поста с авторизацией (должен работать)
POST http://127.0.0.1:8000/api/posts/
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzUwODYxNzA0LCJpYXQiOjE3NTA4NjE0MDQsImp0aSI6IjA3ODQ1ZjUwNDc1MzQ1MzY4NTNkNjM0N2UxYjVlNDk5IiwidXNlcl9pZCI6NjB9.J2UbRFI3SiLkgShE0Kf5YuClY5-rBB1Bs_7x11X1iqY

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="text"

Мой первый пост
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="image"; filename="test.jpg"
Content-Type: image/jpeg

< ./test.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW--

### 3. Тестирование комментариев

### 3.1 Создание комментария без авторизации (должна быть ошибка 401)
POST http://127.0.0.1:8000/api/posts/1/comments/
Content-Type: application/json

{
  "text": "Попытка без авторизации"
}

### 3.2 Создание комментария с авторизацией (должен работать)
POST http://127.0.0.1:8000/api/posts/1/comments/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzUwODYxNzA0LCJpYXQiOjE3NTA4NjE0MDQsImp0aSI6IjA3ODQ1ZjUwNDc1MzQ1MzY4NTNkNjM0N2UxYjVlNDk5IiwidXNlcl9pZCI6NjB9.J2UbRFI3SiLkgShE0Kf5YuClY5-rBB1Bs_7x11X1iqY

{
  "text": "Отличный пост! Класс!!"
}

### 3.3 Просмотр комментариев без авторизации (должен работать)
GET http://127.0.0.1:8000/api/posts/1/comments/
Content-Type: application/json

### 4. Тестирование лайков

### 4.1 Поставить лайк без авторизации (должна быть ошибка 401)
POST http://127.0.0.1:8000/api/posts/1/like/
Content-Type: application/json

### 4.2 Поставить лайк с авторизацией (должен работать)
POST http://127.0.0.1:8000/api/posts/1/like/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzUwODYxNzA0LCJpYXQiOjE3NTA4NjE0MDQsImp0aSI6IjA3ODQ1ZjUwNDc1MzQ1MzY4NTNkNjM0N2UxYjVlNDk5IiwidXNlcl9pZCI6NjB9.J2UbRFI3SiLkgShE0Kf5YuClY5-rBB1Bs_7x11X1iqY

### 4.3 Убрать лайк (повторный запрос)
POST http://127.0.0.1:8000/api/posts/1/like/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzUwODYxNzA0LCJpYXQiOjE3NTA4NjE0MDQsImp0aSI6IjA3ODQ1ZjUwNDc1MzQ1MzY4NTNkNjM0N2UxYjVlNDk5IiwidXNlcl9pZCI6NjB9.J2UbRFI3SiLkgShE0Kf5YuClY5-rBB1Bs_7x11X1iqY

### 5. Тестирование прав доступа

### 5.1 Попытка удалить чужой пост (должна быть ошибка 403)
DELETE http://127.0.0.1:8000/api/posts/1/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzUwODYxNzA0LCJpYXQiOjE3NTA4NjE0MDQsImp0aSI6IjA3ODQ1ZjUwNDc1MzQ1MzY4NTNkNjM0N2UxYjVlNDk5IiwidXNlcl9pZCI6NjB9.J2UbRFI3SiLkgShE0Kf5YuClY5-rBB1Bs_7x11X1iqY

### 5.2 Удаление своего поста (должен работать)
DELETE http://127.0.0.1:8000/api/posts/2/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzUwODYxNzA0LCJpYXQiOjE3NTA4NjE0MDQsImp0aSI6IjA3ODQ1ZjUwNDc1MzQ1MzY4NTNkNjM0N2UxYjVlNDk5IiwidXNlcl9pZCI6NjB9.J2UbRFI3SiLkgShE0Kf5YuClY5-rBB1Bs_7x11X1iqY

### 6. Дополнительные тесты

### 6.1 Просмотр конкретного поста
GET http://127.0.0.1:8000/api/posts/1/
Content-Type: application/json

### 6.2 Фильтрация постов по автору
GET http://127.0.0.1:8000/api/posts/?author=1
Content-Type: application/json